
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

const databaseTarget =
    process.env.DATABASE_TARGET === "postgres" ? "postgres" : "sqlite";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path:
      databaseTarget === "postgres"
        ? "prisma/migrations-postgres"
        : "prisma/migrations-sqlite",
  },
  engine: "classic",
  datasource: {
    url: env("DATABASE_URL"),
  },
});
